# Возврат данных через исключения?
Для возврата из функции некоторой дополнительной информации можно пользоваться [[Обработка исключений|исключениями]], но они сильно тормозят код, вместо этого есть другие способы, например [[variant]]

```cpp
#include "profile.h" 
#include <variant>
#include <vector>
using namespace std; 
enum class FailReason { 
	Bad, 
	Invalid, 
	Ugly, 
	Buggy, 
	Wrong 
}; 
variant<int, FailReason> ComputeCostVariant(int i) { 
	if (i % 10 > 0) { 
		return i * 100; 
	} 
	else { 
		return static_cast(i / 10 % 5); 
	} 
} 
int ComputeCostThrow(int i) { 
	if (i % 10 > 0) { 
		return i * 100; 
} 
	else { 
		throw static_cast(i / 10 % 5);
	} 
} 
const int ITER_COUNT = 1000000;

int main() { 
	vector<int> stats(6); 
	{ 
		LOG_DURATION("variant"); 
		for (int i = 0; i < ITER_COUNT; ++i) { 
			if (const auto res = ComputeCostVariant(i); holds_alternative(res)) 
			{ 
				++stats[static_cast(get(res))]; 
			} 
			else { 
				stats.back() += get(res); 
			} 
		} 
	} 
	{ 
		LOG_DURATION("throw"); 
		for (int i = 0; i < ITER_COUNT; ++i) { 
			try { 
				stats.back() += ComputeCostThrow(i); 
			} catch(const FailReason reason) { 
				++stats[static_cast(reason)]; 
			} 
		} 
	} 
	return 0; 
}
// variant: 64 ms
// throw: 47905 ms
```