# Механизм обработки исключений
```cpp
void A()
{	
	ifstream fstr("output.txt");
	if (!fstr)
		throw exception{ "file not found" };
	//...
}



int main(int argc, char* argv[])
{
	try
	{
		A();
	}
	catch (const exception& e)
	{
		cout << e.what();
	}
}
```

```plantuml
start 
:Вызваем функцию A(), 
пытаемся открыть файл для ввода; 
if (Пытаемся открыть файл) then(Файла нет)
	:Выбрасываем исключения: "Файл не найден";
	:Вызывающая сторона ловит его и обрабатывает 
	с помощью блока try/catch,выводя информацию 
	об исключении; 
else (Файл есть)
	:Работаем с файлом;
	:Закрываем его и передаем управление в main;
stop 
endif 
stop
```

1. Блок try предназначен для того, что после выброса исключения ваша программа не упала
2. Блок catch предназначен для обработки исключений, если исключений не было выброшено, блок try не выполняется