# Раскрутка стека при выбросе исключения
Когда выбрасывается исключение, программа идет вверх по фреймам и ищет блок catch, чтобы обработать, его может совсем не быть, тогда программа `terminate`, а может быть несколько. Когда блок найден, происходит раскрутка стека - уничтожаются все локальные переменные фреймов начиная с самой вершины стека и до фрейма содержащего блок catch(не включительно). Из-за этого, может произойти утечка памяти:

```cpp
void funcOne();
void funcTwo();
int main()
{
	try {
		funcOne();
	}
	catch (const exception& e) {
		cerr << "Exception caught!" << endl;
		return 1;
	}
}
void funcOne()
{
	string str1;
	string* str2{ new string {} };
	funcTwo();
	delete str2;//Программа никогда не дойдет до этой строчки, стоит использовать умные указатели, чтобы деструктор сам вызвался
}
void funcTwo()
{
	ifstream fileStream;
	fileStream.open("filename");
	throw exception{};
	fileStream.close();//до этой строчки не дойдет, но во время раскрутки стека поток все равно закроется тк ifstream локальная переменная
}
```